# Generated by Django 4.2.2 on 2023-07-04 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('food_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_foods', to='vendor.vendor')),
            ],
        ),
    ]
